// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs
// REQUIRES: x86-registered-target
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -verify -fopenmp -fopenmp-taskgraph -emit-llvm \
// RUN:    -emit-llvm -o - %s  -disable-llvm-passes | FileCheck --check-prefixes=CHECK %s
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -verify -fopenmp  -fopenmp-taskgraph \
// RUN:    -emit-llvm -debug-info-kind=limited %s  -o - -disable-llvm-passes | \
// RUN:    FileCheck --check-prefixes=CHECK-DEBUG %s

// Next line is for -verify
// expected-no-diagnostics

extern void foo();

void empty_taskgraph(void) {
#pragma omp taskgraph
  {
    foo();
  }
}

void one_task(void) {
#pragma omp taskgraph
  {
#pragma omp task
    {
      foo();
    }
  }
}

void loop_of_tasks(int N) {
#pragma omp taskgraph
  {
    for (int i = 0; i < N; i++)
#pragma omp task
    {
      foo();
    }
  }
}
// CHECK-O0-LABEL: @_Z15empty_taskgraphv(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON:%.*]], align 1
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1:@.*]])
// CHECK-O0-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon* [[AGG_CAPTURED]] to i8*
// CHECK-O0-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon*)* @__captured_stmt to i8*), i8* [[TMP1]], i32 0)
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @__captured_stmt(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon*, align 8
// CHECK-O0-NEXT:    store %struct.anon* [[__CONTEXT:%.*]], %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load %struct.anon*, %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    call void @_Z3foov()
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @_Z8one_taskv(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_0:%.*]], align 1
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O0-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon.0* [[AGG_CAPTURED]] to i8*
// CHECK-O0-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.0*)* @__captured_stmt.1 to i8*), i8* [[TMP1]], i32 0)
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @__captured_stmt.1(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.0*, align 8
// CHECK-O0-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_1:%.*]], align 1
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O0-NEXT:    store %struct.anon.0* [[__CONTEXT:%.*]], %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = load %struct.anon.0*, %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates*)* @.omp_task_entry. to i32 (i32, i8*)*))
// CHECK-O0-NEXT:    [[TMP3:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 1
// CHECK-O0-NEXT:    store i32 [[TMP4]], i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP2]], i32 [[TMP4]])
// CHECK-O0-NEXT:    [[TMP5:%.*]] = bitcast i8* [[TMP2]] to %struct.kmp_task_t_with_privates*
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP5]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP2]])
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @.omp_outlined.(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-O0-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O0-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-O0-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O0-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.1*, align 8
// CHECK-O0-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-O0-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-O0-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-O0-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-O0-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-O0-NEXT:    store %struct.anon.1* [[__CONTEXT:%.*]], %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load %struct.anon.1*, %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    call void @_Z3foov()
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @.omp_task_entry.(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates*, align 8
// CHECK-O0-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-O0-NEXT:    store %struct.kmp_task_t_with_privates* [[TMP1:%.*]], %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates*, %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP3]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.1*
// CHECK-O0-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates* [[TMP3]] to i8*
// CHECK-O0-NEXT:    call void @.omp_outlined.(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.1* [[TMP8]]) [[ATTR3:#.*]]
// CHECK-O0-NEXT:    ret i32 0
// CHECK-O0-LABEL: @_Z13loop_of_tasksi(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_2:%.*]], align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O0-NEXT:    store i32 [[N:%.*]], i32* [[N_ADDR]], align 4
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_ANON_2]], %struct.anon.2* [[AGG_CAPTURED]], i32 0, i32 0
// CHECK-O0-NEXT:    store i32* [[N_ADDR]], i32** [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = bitcast %struct.anon.2* [[AGG_CAPTURED]] to i8*
// CHECK-O0-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.2*)* @__captured_stmt.2 to i8*), i8* [[TMP2]], i32 0)
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @__captured_stmt.2(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.2*, align 8
// CHECK-O0-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_3:%.*]], align 1
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O0-NEXT:    store %struct.anon.2* [[__CONTEXT:%.*]], %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = load %struct.anon.2*, %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    store i32 0, i32* [[I]], align 4
// CHECK-O0-NEXT:    br label [[FOR_COND:%.*]]
// CHECK-O0:       for.cond:
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, i32* [[I]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [[STRUCT_ANON_2:%.*]], %struct.anon.2* [[TMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP4:%.*]] = load i32*, i32** [[TMP3]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = load i32, i32* [[TMP4]], align 4
// CHECK-O0-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP2]], [[TMP5]]
// CHECK-O0-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK-O0:       for.body:
// CHECK-O0-NEXT:    [[TMP6:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates.4*)* @.omp_task_entry..4 to i32 (i32, i8*)*))
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], 1
// CHECK-O0-NEXT:    store i32 [[TMP8]], i32* @__staticTaskID, align 4
// CHECK-O0-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP6]], i32 [[TMP8]])
// CHECK-O0-NEXT:    [[TMP9:%.*]] = bitcast i8* [[TMP6]] to %struct.kmp_task_t_with_privates.4*
// CHECK-O0-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP9]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP11:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP6]])
// CHECK-O0-NEXT:    br label [[FOR_INC:%.*]]
// CHECK-O0:       for.inc:
// CHECK-O0-NEXT:    [[TMP12:%.*]] = load i32, i32* [[I]], align 4
// CHECK-O0-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP12]], 1
// CHECK-O0-NEXT:    store i32 [[INC]], i32* [[I]], align 4
// CHECK-O0-NEXT:    br label [[FOR_COND]], [[LOOP2:!llvm.loop !.*]]
// CHECK-O0:       for.end:
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @.omp_outlined..3(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-O0-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O0-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-O0-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O0-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.3*, align 8
// CHECK-O0-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-O0-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-O0-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-O0-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-O0-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-O0-NEXT:    store %struct.anon.3* [[__CONTEXT:%.*]], %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    [[TMP0:%.*]] = load %struct.anon.3*, %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-O0-NEXT:    call void @_Z3foov()
// CHECK-O0-NEXT:    ret void
// CHECK-O0-LABEL: @.omp_task_entry..4(
// CHECK-O0-NEXT:  entry:
// CHECK-O0-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates.4*, align 8
// CHECK-O0-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-O0-NEXT:    store %struct.kmp_task_t_with_privates.4* [[TMP1:%.*]], %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4
// CHECK-O0-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates.4*, %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP3]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.3*
// CHECK-O0-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates.4* [[TMP3]] to i8*
// CHECK-O0-NEXT:    call void @.omp_outlined..3(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.3* [[TMP8]]) [[ATTR3]]
// CHECK-O0-NEXT:    ret i32 0
// CHECK-O2-LABEL: @_Z15empty_taskgraphv(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON:%.*]], align 1
// CHECK-O2-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1:@.*]])
// CHECK-O2-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon* [[AGG_CAPTURED]] to i8*
// CHECK-O2-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon*)* @__captured_stmt to i8*), i8* [[TMP1]], i32 0)
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @__captured_stmt(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon*, align 8
// CHECK-O2-NEXT:    store %struct.anon* [[__CONTEXT:%.*]], %struct.anon** [[__CONTEXT_ADDR]], align 8, [[TBAA2:!tbaa !.*]]
// CHECK-O2-NEXT:    [[TMP0:%.*]] = load %struct.anon*, %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-O2-NEXT:    call void @_Z3foov()
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @_Z8one_taskv(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_0:%.*]], align 1
// CHECK-O2-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O2-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon.0* [[AGG_CAPTURED]] to i8*
// CHECK-O2-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.0*)* @__captured_stmt.1 to i8*), i8* [[TMP1]], i32 0)
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @__captured_stmt.1(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.0*, align 8
// CHECK-O2-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_1:%.*]], align 1
// CHECK-O2-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O2-NEXT:    store %struct.anon.0* [[__CONTEXT:%.*]], %struct.anon.0** [[__CONTEXT_ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP1:%.*]] = load %struct.anon.0*, %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-O2-NEXT:    [[TMP2:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates*)* @.omp_task_entry. to i32 (i32, i8*)*))
// CHECK-O2-NEXT:    [[TMP3:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 1
// CHECK-O2-NEXT:    store i32 [[TMP4]], i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP2]], i32 [[TMP4]])
// CHECK-O2-NEXT:    [[TMP5:%.*]] = bitcast i8* [[TMP2]] to %struct.kmp_task_t_with_privates*
// CHECK-O2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP5]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP7:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP2]])
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @.omp_outlined.(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-O2-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O2-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-O2-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O2-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.1*, align 8
// CHECK-O2-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4, [[TBAA6:!tbaa !.*]]
// CHECK-O2-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store %struct.anon.1* [[__CONTEXT:%.*]], %struct.anon.1** [[__CONTEXT_ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP0:%.*]] = load %struct.anon.1*, %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-O2-NEXT:    call void @_Z3foov()
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @.omp_task_entry.(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates*, align 8
// CHECK-O2-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    store %struct.kmp_task_t_with_privates* [[TMP1:%.*]], %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates*, %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-O2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP3]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-O2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8, [[TBAA8:!tbaa !.*]]
// CHECK-O2-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.1*
// CHECK-O2-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates* [[TMP3]] to i8*
// CHECK-O2-NEXT:    call void @.omp_outlined.(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.1* [[TMP8]]) [[ATTR3:#.*]]
// CHECK-O2-NEXT:    ret i32 0
// CHECK-O2-LABEL: @_Z13loop_of_tasksi(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_2:%.*]], align 8
// CHECK-O2-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O2-NEXT:    store i32 [[N:%.*]], i32* [[N_ADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_ANON_2]], %struct.anon.2* [[AGG_CAPTURED]], i32 0, i32 0
// CHECK-O2-NEXT:    store i32* [[N_ADDR]], i32** [[TMP1]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP2:%.*]] = bitcast %struct.anon.2* [[AGG_CAPTURED]] to i8*
// CHECK-O2-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.2*)* @__captured_stmt.2 to i8*), i8* [[TMP2]], i32 0)
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @__captured_stmt.2(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.2*, align 8
// CHECK-O2-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_3:%.*]], align 1
// CHECK-O2-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-O2-NEXT:    store %struct.anon.2* [[__CONTEXT:%.*]], %struct.anon.2** [[__CONTEXT_ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP1:%.*]] = load %struct.anon.2*, %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-O2-NEXT:    [[TMP2:%.*]] = bitcast i32* [[I]] to i8*
// CHECK-O2-NEXT:    call void @llvm.lifetime.start.p0i8(i64 4, i8* [[TMP2]]) [[ATTR3]]
// CHECK-O2-NEXT:    store i32 0, i32* [[I]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    br label [[FOR_COND:%.*]]
// CHECK-O2:       for.cond:
// CHECK-O2-NEXT:    [[TMP3:%.*]] = load i32, i32* [[I]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_ANON_2:%.*]], %struct.anon.2* [[TMP1]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP5:%.*]] = load i32*, i32** [[TMP4]], align 8, [[TBAA11:!tbaa !.*]]
// CHECK-O2-NEXT:    [[TMP6:%.*]] = load i32, i32* [[TMP5]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP3]], [[TMP6]]
// CHECK-O2-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK-O2:       for.cond.cleanup:
// CHECK-O2-NEXT:    [[TMP7:%.*]] = bitcast i32* [[I]] to i8*
// CHECK-O2-NEXT:    call void @llvm.lifetime.end.p0i8(i64 4, i8* [[TMP7]]) [[ATTR3]]
// CHECK-O2-NEXT:    br label [[FOR_END:%.*]]
// CHECK-O2:       for.body:
// CHECK-O2-NEXT:    [[TMP8:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates.4*)* @.omp_task_entry..4 to i32 (i32, i8*)*))
// CHECK-O2-NEXT:    [[TMP9:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    [[TMP10:%.*]] = add i32 [[TMP9]], 1
// CHECK-O2-NEXT:    store i32 [[TMP10]], i32* @__staticTaskID, align 4
// CHECK-O2-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP8]], i32 [[TMP10]])
// CHECK-O2-NEXT:    [[TMP11:%.*]] = bitcast i8* [[TMP8]] to %struct.kmp_task_t_with_privates.4*
// CHECK-O2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP11]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP13:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP8]])
// CHECK-O2-NEXT:    br label [[FOR_INC:%.*]]
// CHECK-O2:       for.inc:
// CHECK-O2-NEXT:    [[TMP14:%.*]] = load i32, i32* [[I]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP14]], 1
// CHECK-O2-NEXT:    store i32 [[INC]], i32* [[I]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    br label [[FOR_COND]], [[LOOP13:!llvm.loop !.*]]
// CHECK-O2:       for.end:
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @.omp_outlined..3(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-O2-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O2-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-O2-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-O2-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.3*, align 8
// CHECK-O2-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    store %struct.anon.3* [[__CONTEXT:%.*]], %struct.anon.3** [[__CONTEXT_ADDR]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP0:%.*]] = load %struct.anon.3*, %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-O2-NEXT:    call void @_Z3foov()
// CHECK-O2-NEXT:    ret void
// CHECK-O2-LABEL: @.omp_task_entry..4(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-O2-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates.4*, align 8
// CHECK-O2-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    store %struct.kmp_task_t_with_privates.4* [[TMP1:%.*]], %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8, [[TBAA2]]
// CHECK-O2-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4, [[TBAA6]]
// CHECK-O2-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates.4*, %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-O2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP3]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-O2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-O2-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8, [[TBAA8]]
// CHECK-O2-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.3*
// CHECK-O2-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates.4* [[TMP3]] to i8*
// CHECK-O2-NEXT:    call void @.omp_outlined..3(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.3* [[TMP8]]) [[ATTR3]]
// CHECK-O2-NEXT:    ret i32 0
// CHECK-LABEL: @_Z15empty_taskgraphv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON:%.*]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1:@.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon* [[AGG_CAPTURED]] to i8*
// CHECK-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon*)* @__captured_stmt to i8*), i8* [[TMP1]], i32 0)
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @__captured_stmt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon*, align 8
// CHECK-NEXT:    store %struct.anon* [[__CONTEXT:%.*]], %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load %struct.anon*, %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    call void @_Z3foov()
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @_Z8one_taskv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_0:%.*]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon.0* [[AGG_CAPTURED]] to i8*
// CHECK-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.0*)* @__captured_stmt.1 to i8*), i8* [[TMP1]], i32 0)
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @__captured_stmt.1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.0*, align 8
// CHECK-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_1:%.*]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-NEXT:    store %struct.anon.0* [[__CONTEXT:%.*]], %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load %struct.anon.0*, %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates*)* @.omp_task_entry. to i32 (i32, i8*)*))
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 1
// CHECK-NEXT:    store i32 [[TMP4]], i32* @__staticTaskID, align 4
// CHECK-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP2]], i32 [[TMP4]])
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast i8* [[TMP2]] to %struct.kmp_task_t_with_privates*
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP5]], i32 0, i32 0
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP2]])
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @.omp_outlined.(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.1*, align 8
// CHECK-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-NEXT:    store %struct.anon.1* [[__CONTEXT:%.*]], %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load %struct.anon.1*, %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    call void @_Z3foov()
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @.omp_task_entry.(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates*, align 8
// CHECK-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-NEXT:    store %struct.kmp_task_t_with_privates* [[TMP1:%.*]], %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates*, %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP3]], i32 0, i32 0
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.1*
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates* [[TMP3]] to i8*
// CHECK-NEXT:    call void @.omp_outlined.(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.1* [[TMP8]]) [[ATTR3:#.*]]
// CHECK-NEXT:    ret i32 0
//
//
// CHECK-LABEL: @_Z13loop_of_tasksi(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_2:%.*]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-NEXT:    store i32 [[N:%.*]], i32* [[N_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_ANON_2]], %struct.anon.2* [[AGG_CAPTURED]], i32 0, i32 0
// CHECK-NEXT:    store i32* [[N_ADDR]], i32** [[TMP1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast %struct.anon.2* [[AGG_CAPTURED]] to i8*
// CHECK-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.2*)* @__captured_stmt.2 to i8*), i8* [[TMP2]], i32 0)
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @__captured_stmt.2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.2*, align 8
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_3:%.*]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1]])
// CHECK-NEXT:    store %struct.anon.2* [[__CONTEXT:%.*]], %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load %struct.anon.2*, %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    store i32 0, i32* [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [[STRUCT_ANON_2:%.*]], %struct.anon.2* [[TMP1]], i32 0, i32 0
// CHECK-NEXT:    [[TMP4:%.*]] = load i32*, i32** [[TMP3]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, i32* [[TMP4]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP2]], [[TMP5]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP6:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates.4*)* @.omp_task_entry..4 to i32 (i32, i8*)*))
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, i32* @__staticTaskID, align 4
// CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], 1
// CHECK-NEXT:    store i32 [[TMP8]], i32* @__staticTaskID, align 4
// CHECK-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP6]], i32 [[TMP8]])
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast i8* [[TMP6]] to %struct.kmp_task_t_with_privates.4*
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP9]], i32 0, i32 0
// CHECK-NEXT:    [[TMP11:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* [[TMP6]])
// CHECK-NEXT:    br label [[FOR_INC:%.*]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP12]], 1
// CHECK-NEXT:    store i32 [[INC]], i32* [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND]], [[LOOP2:!llvm.loop !.*]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @.omp_outlined..3(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.3*, align 8
// CHECK-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-NEXT:    store %struct.anon.3* [[__CONTEXT:%.*]], %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load %struct.anon.3*, %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-NEXT:    call void @_Z3foov()
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: @.omp_task_entry..4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates.4*, align 8
// CHECK-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-NEXT:    store %struct.kmp_task_t_with_privates.4* [[TMP1:%.*]], %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates.4*, %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP3]], i32 0, i32 0
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0
// CHECK-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.3*
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates.4* [[TMP3]] to i8*
// CHECK-NEXT:    call void @.omp_outlined..3(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.3* [[TMP8]]) [[ATTR3]]
// CHECK-NEXT:    ret i32 0
//
//
// CHECK-DEBUG-LABEL: @_Z15empty_taskgraphv(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON:%.*]], align 1
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB1:@.*]])
// CHECK-DEBUG-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon* [[AGG_CAPTURED]] to i8*, [[DBG10:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB1]], i32 [[TMP0]], i8* bitcast (void (%struct.anon*)* @__captured_stmt to i8*), i8* [[TMP1]], i32 0), [[DBG10]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG11:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @__captured_stmt(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-DEBUG-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon*, align 8
// CHECK-DEBUG-NEXT:    store %struct.anon* [[__CONTEXT:%.*]], %struct.anon** [[__CONTEXT_ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.anon** [[__CONTEXT_ADDR]], [[META20:metadata !.*]], metadata !DIExpression()), [[DBG21:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = load %struct.anon*, %struct.anon** [[__CONTEXT_ADDR]], align 8, [[DBG22:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @_Z3foov(), [[DBG24:!dbg !.*]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG26:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @_Z8one_taskv(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_0:%.*]], align 1
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB5:@.*]])
// CHECK-DEBUG-NEXT:    [[TMP1:%.*]] = bitcast %struct.anon.0* [[AGG_CAPTURED]] to i8*, [[DBG28:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB5]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.0*)* @__captured_stmt.1 to i8*), i8* [[TMP1]], i32 0), [[DBG28]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG29:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @__captured_stmt.1(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-DEBUG-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.0*, align 8
// CHECK-DEBUG-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_1:%.*]], align 1
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB3:@.*]])
// CHECK-DEBUG-NEXT:    store %struct.anon.0* [[__CONTEXT:%.*]], %struct.anon.0** [[__CONTEXT_ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.anon.0** [[__CONTEXT_ADDR]], [[META37:metadata !.*]], metadata !DIExpression()), [[DBG38:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP1:%.*]] = load %struct.anon.0*, %struct.anon.0** [[__CONTEXT_ADDR]], align 8, [[DBG39:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP2:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB3]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates*)* @.omp_task_entry. to i32 (i32, i8*)*)), [[DBG41:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP3:%.*]] = load i32, i32* @__staticTaskID, align 4, [[DBG41]]
// CHECK-DEBUG-NEXT:    [[TMP4:%.*]] = add i32 [[TMP3]], 1, [[DBG41]]
// CHECK-DEBUG-NEXT:    store i32 [[TMP4]], i32* @__staticTaskID, align 4, [[DBG41]]
// CHECK-DEBUG-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP2]], i32 [[TMP4]]), [[DBG41]]
// CHECK-DEBUG-NEXT:    [[TMP5:%.*]] = bitcast i8* [[TMP2]] to %struct.kmp_task_t_with_privates*, [[DBG41]]
// CHECK-DEBUG-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP5]], i32 0, i32 0, [[DBG41]]
// CHECK-DEBUG-NEXT:    [[TMP7:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB3]], i32 [[TMP0]], i8* [[TMP2]]), [[DBG41]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG43:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @.omp_outlined.(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-DEBUG-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-DEBUG-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-DEBUG-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-DEBUG-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.1*, align 8
// CHECK-DEBUG-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[DOTGLOBAL_TID__ADDR]], [[META65:metadata !.*]], metadata !DIExpression()), [[DBG66:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32** [[DOTPART_ID__ADDR]], [[META67:metadata !.*]], metadata !DIExpression()), [[DBG66]]
// CHECK-DEBUG-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i8** [[DOTPRIVATES__ADDR]], [[META68:metadata !.*]], metadata !DIExpression()), [[DBG66]]
// CHECK-DEBUG-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata void (i8*, ...)** [[DOTCOPY_FN__ADDR]], [[META69:metadata !.*]], metadata !DIExpression()), [[DBG66]]
// CHECK-DEBUG-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i8** [[DOTTASK_T__ADDR]], [[META70:metadata !.*]], metadata !DIExpression()), [[DBG66]]
// CHECK-DEBUG-NEXT:    store %struct.anon.1* [[__CONTEXT:%.*]], %struct.anon.1** [[__CONTEXT_ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.anon.1** [[__CONTEXT_ADDR]], [[META71:metadata !.*]], metadata !DIExpression()), [[DBG66]]
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = load %struct.anon.1*, %struct.anon.1** [[__CONTEXT_ADDR]], align 8, [[DBG72:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @_Z3foov(), [[DBG74:!dbg !.*]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG76:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @.omp_task_entry.(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates*, align 8
// CHECK-DEBUG-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[DOTADDR]], [[META79:metadata !.*]], metadata !DIExpression()), [[DBG80:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store %struct.kmp_task_t_with_privates* [[TMP1:%.*]], %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.kmp_task_t_with_privates** [[DOTADDR1]], [[META81:metadata !.*]], metadata !DIExpression()), [[DBG80]]
// CHECK-DEBUG-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4, [[DBG85:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates*, %struct.kmp_task_t_with_privates** [[DOTADDR1]], align 8, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], %struct.kmp_task_t_with_privates* [[TMP3]], i32 0, i32 0, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.1*, [[DBG85]]
// CHECK-DEBUG-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates* [[TMP3]] to i8*, [[DBG85]]
// CHECK-DEBUG-NEXT:    call void @.omp_outlined.(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.1* [[TMP8]]) [[ATTR4:#.*]], [[DBG85]]
// CHECK-DEBUG-NEXT:    ret i32 0, [[DBG85]]
//
//
// CHECK-DEBUG-LABEL: @_Z13loop_of_tasksi(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_2:%.*]], align 8
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB9:@.*]])
// CHECK-DEBUG-NEXT:    store i32 [[N:%.*]], i32* [[N_ADDR]], align 4
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[N_ADDR]], [[META89:metadata !.*]], metadata !DIExpression()), [[DBG90:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [[STRUCT_ANON_2]], %struct.anon.2* [[AGG_CAPTURED]], i32 0, i32 0, [[DBG91:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store i32* [[N_ADDR]], i32** [[TMP1]], align 8, [[DBG91]]
// CHECK-DEBUG-NEXT:    [[TMP2:%.*]] = bitcast %struct.anon.2* [[AGG_CAPTURED]] to i8*, [[DBG91]]
// CHECK-DEBUG-NEXT:    call void @__kmpc_taskgraph(%struct.ident_t* [[GLOB9]], i32 [[TMP0]], i8* bitcast (void (%struct.anon.2*)* @__captured_stmt.2 to i8*), i8* [[TMP2]], i32 0), [[DBG91]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG92:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @__captured_stmt.2(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    store i32 0, i32* @__staticTaskID, align 4
// CHECK-DEBUG-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.2*, align 8
// CHECK-DEBUG-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON_3:%.*]], align 1
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(%struct.ident_t* [[GLOB7:@.*]])
// CHECK-DEBUG-NEXT:    store %struct.anon.2* [[__CONTEXT:%.*]], %struct.anon.2** [[__CONTEXT_ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.anon.2** [[__CONTEXT_ADDR]], [[META100:metadata !.*]], metadata !DIExpression()), [[DBG101:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP1:%.*]] = load %struct.anon.2*, %struct.anon.2** [[__CONTEXT_ADDR]], align 8, [[DBG102:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[I]], [[META104:metadata !.*]], metadata !DIExpression()), [[DBG107:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store i32 0, i32* [[I]], align 4, [[DBG107]]
// CHECK-DEBUG-NEXT:    br label [[FOR_COND:%.*]], [[DBG108:!dbg !.*]]
// CHECK-DEBUG:       for.cond:
// CHECK-DEBUG-NEXT:    [[TMP2:%.*]] = load i32, i32* [[I]], align 4, [[DBG109:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [[STRUCT_ANON_2:%.*]], %struct.anon.2* [[TMP1]], i32 0, i32 0, [[DBG111:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP4:%.*]] = load i32*, i32** [[TMP3]], align 8, [[DBG111]]
// CHECK-DEBUG-NEXT:    [[TMP5:%.*]] = load i32, i32* [[TMP4]], align 4, [[DBG111]]
// CHECK-DEBUG-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP2]], [[TMP5]], [[DBG112:!dbg !.*]]
// CHECK-DEBUG-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]], [[DBG113:!dbg !.*]]
// CHECK-DEBUG:       for.body:
// CHECK-DEBUG-NEXT:    [[TMP6:%.*]] = call i8* @__kmpc_omp_task_alloc(%struct.ident_t* [[GLOB7]], i32 [[TMP0]], i32 1, i64 40, i64 1, i32 (i32, i8*)* bitcast (i32 (i32, %struct.kmp_task_t_with_privates.4*)* @.omp_task_entry..4 to i32 (i32, i8*)*)), [[DBG114:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP7:%.*]] = load i32, i32* @__staticTaskID, align 4, [[DBG114]]
// CHECK-DEBUG-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], 1, [[DBG114]]
// CHECK-DEBUG-NEXT:    store i32 [[TMP8]], i32* @__staticTaskID, align 4, [[DBG114]]
// CHECK-DEBUG-NEXT:    call void @__kmpc_set_task_static_id(i8* [[TMP6]], i32 [[TMP8]]), [[DBG114]]
// CHECK-DEBUG-NEXT:    [[TMP9:%.*]] = bitcast i8* [[TMP6]] to %struct.kmp_task_t_with_privates.4*, [[DBG114]]
// CHECK-DEBUG-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP9]], i32 0, i32 0, [[DBG114]]
// CHECK-DEBUG-NEXT:    [[TMP11:%.*]] = call i32 @__kmpc_omp_task(%struct.ident_t* [[GLOB7]], i32 [[TMP0]], i8* [[TMP6]]), [[DBG114]]
// CHECK-DEBUG-NEXT:    br label [[FOR_INC:%.*]], [[DBG115:!dbg !.*]]
// CHECK-DEBUG:       for.inc:
// CHECK-DEBUG-NEXT:    [[TMP12:%.*]] = load i32, i32* [[I]], align 4, [[DBG117:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP12]], 1, [[DBG117]]
// CHECK-DEBUG-NEXT:    store i32 [[INC]], i32* [[I]], align 4, [[DBG117]]
// CHECK-DEBUG-NEXT:    br label [[FOR_COND]], [[DBG118:!dbg !.*]], [[LOOP119:!llvm.loop !.*]]
// CHECK-DEBUG:       for.end:
// CHECK-DEBUG-NEXT:    ret void, [[DBG122:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @.omp_outlined..3(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[DOTGLOBAL_TID__ADDR:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[DOTPART_ID__ADDR:%.*]] = alloca i32*, align 8
// CHECK-DEBUG-NEXT:    [[DOTPRIVATES__ADDR:%.*]] = alloca i8*, align 8
// CHECK-DEBUG-NEXT:    [[DOTCOPY_FN__ADDR:%.*]] = alloca void (i8*, ...)*, align 8
// CHECK-DEBUG-NEXT:    [[DOTTASK_T__ADDR:%.*]] = alloca i8*, align 8
// CHECK-DEBUG-NEXT:    [[__CONTEXT_ADDR:%.*]] = alloca %struct.anon.3*, align 8
// CHECK-DEBUG-NEXT:    store i32 [[DOTGLOBAL_TID_:%.*]], i32* [[DOTGLOBAL_TID__ADDR]], align 4
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[DOTGLOBAL_TID__ADDR]], [[META130:metadata !.*]], metadata !DIExpression()), [[DBG131:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store i32* [[DOTPART_ID_:%.*]], i32** [[DOTPART_ID__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32** [[DOTPART_ID__ADDR]], [[META132:metadata !.*]], metadata !DIExpression()), [[DBG131]]
// CHECK-DEBUG-NEXT:    store i8* [[DOTPRIVATES_:%.*]], i8** [[DOTPRIVATES__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i8** [[DOTPRIVATES__ADDR]], [[META133:metadata !.*]], metadata !DIExpression()), [[DBG131]]
// CHECK-DEBUG-NEXT:    store void (i8*, ...)* [[DOTCOPY_FN_:%.*]], void (i8*, ...)** [[DOTCOPY_FN__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata void (i8*, ...)** [[DOTCOPY_FN__ADDR]], [[META134:metadata !.*]], metadata !DIExpression()), [[DBG131]]
// CHECK-DEBUG-NEXT:    store i8* [[DOTTASK_T_:%.*]], i8** [[DOTTASK_T__ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i8** [[DOTTASK_T__ADDR]], [[META135:metadata !.*]], metadata !DIExpression()), [[DBG131]]
// CHECK-DEBUG-NEXT:    store %struct.anon.3* [[__CONTEXT:%.*]], %struct.anon.3** [[__CONTEXT_ADDR]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.anon.3** [[__CONTEXT_ADDR]], [[META136:metadata !.*]], metadata !DIExpression()), [[DBG131]]
// CHECK-DEBUG-NEXT:    [[TMP0:%.*]] = load %struct.anon.3*, %struct.anon.3** [[__CONTEXT_ADDR]], align 8, [[DBG137:!dbg !.*]]
// CHECK-DEBUG-NEXT:    call void @_Z3foov(), [[DBG139:!dbg !.*]]
// CHECK-DEBUG-NEXT:    ret void, [[DBG141:!dbg !.*]]
//
//
// CHECK-DEBUG-LABEL: @.omp_task_entry..4(
// CHECK-DEBUG-NEXT:  entry:
// CHECK-DEBUG-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CHECK-DEBUG-NEXT:    [[DOTADDR1:%.*]] = alloca %struct.kmp_task_t_with_privates.4*, align 8
// CHECK-DEBUG-NEXT:    store i32 [[TMP0:%.*]], i32* [[DOTADDR]], align 4
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata i32* [[DOTADDR]], [[META143:metadata !.*]], metadata !DIExpression()), [[DBG144:!dbg !.*]]
// CHECK-DEBUG-NEXT:    store %struct.kmp_task_t_with_privates.4* [[TMP1:%.*]], %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8
// CHECK-DEBUG-NEXT:    call void @llvm.dbg.declare(metadata %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], [[META145:metadata !.*]], metadata !DIExpression()), [[DBG144]]
// CHECK-DEBUG-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTADDR]], align 4, [[DBG146:!dbg !.*]]
// CHECK-DEBUG-NEXT:    [[TMP3:%.*]] = load %struct.kmp_task_t_with_privates.4*, %struct.kmp_task_t_with_privates.4** [[DOTADDR1]], align 8, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T_WITH_PRIVATES_4:%.*]], %struct.kmp_task_t_with_privates.4* [[TMP3]], i32 0, i32 0, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T:%.*]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 2, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KMP_TASK_T]], %struct.kmp_task_t* [[TMP4]], i32 0, i32 0, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP7:%.*]] = load i8*, i8** [[TMP6]], align 8, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP8:%.*]] = bitcast i8* [[TMP7]] to %struct.anon.3*, [[DBG146]]
// CHECK-DEBUG-NEXT:    [[TMP9:%.*]] = bitcast %struct.kmp_task_t_with_privates.4* [[TMP3]] to i8*, [[DBG146]]
// CHECK-DEBUG-NEXT:    call void @.omp_outlined..3(i32 [[TMP2]], i32* [[TMP5]], i8* null, void (i8*, ...)* null, i8* [[TMP9]], %struct.anon.3* [[TMP8]]) [[ATTR4]], [[DBG146]]
// CHECK-DEBUG-NEXT:    ret i32 0, [[DBG146]]
//
